from io import BytesIO

import barcode
from barcode.writer import ImageWriter
from PIL import Image, ImageDraw, ImageFont


def _load_font(size, bold=False):
    font_names = ["DejaVuSans-Bold.ttf", "arialbd.ttf"] if bold else ["DejaVuSans.ttf", "arial.ttf"]
    for font_name in font_names:
        try:
            return ImageFont.truetype(font_name, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


def build_barcode_image(reference_code):
    code128 = barcode.get("code128", reference_code, writer=ImageWriter())
    barcode_buffer = BytesIO()
    code128.write(
        barcode_buffer,
        options={
            "module_width": 0.28,
            "module_height": 18,
            "font_size": 14,
            "text_distance": 6,
            "quiet_zone": 2,
        },
    )
    barcode_buffer.seek(0)
    return Image.open(barcode_buffer).convert("RGB")


def build_ticket_pdf(ticket):
    width, height = 1240, 1754
    canvas = Image.new("RGB", (width, height), "#f7f1e8")
    draw = ImageDraw.Draw(canvas)

    draw.rounded_rectangle((70, 70, width - 70, height - 70), radius=36, fill="white", outline="#d8c4a6", width=4)
    draw.rounded_rectangle((70, 70, width - 70, 290), radius=36, fill="#163020")
    draw.text((120, 120), "Golden Dragon Tours", font=_load_font(54, bold=True), fill="white")
    draw.text((120, 190), "Digital Travel Ticket", font=_load_font(30), fill="#f3dfc1")

    draw.rounded_rectangle((120, 340, width - 120, 980), radius=28, fill="#fbf7f1", outline="#eadcc8", width=3)
    draw.text((150, 385), "Booking Details", font=_load_font(34, bold=True), fill="#163020")

    details = [
        ("Reference Code", ticket.reference_code),
        ("Guest Name", ticket.full_name),
        ("Email", ticket.email),
        ("Phone", ticket.phone),
        ("Nationality", ticket.nationality),
        ("Tour Package", ticket.tour_package.name if ticket.tour_package else "Not selected"),
        ("Travel Date", ticket.travel_date.strftime("%B %d, %Y")),
        ("Quantity", str(ticket.quantity)),
        ("Status", ticket.get_status_display()),
    ]

    y = 455
    for label, value in details:
        draw.text((160, y), label, font=_load_font(24, bold=True), fill="#8a6f4d")
        draw.text((160, y + 38), str(value), font=_load_font(30), fill="#1f1f1f")
        y += 95

    draw.rounded_rectangle((120, 1035, width - 120, 1510), radius=28, fill="#fffdfa", outline="#eadcc8", width=3)
    draw.text((150, 1080), "Entry Barcode", font=_load_font(34, bold=True), fill="#163020")
    draw.text((150, 1135), "Present this PDF or the on-screen ticket at the point of entry.", font=_load_font(24), fill="#6a6258")

    barcode_image = build_barcode_image(ticket.reference_code)
    max_barcode_width = width - 360
    barcode_ratio = max_barcode_width / barcode_image.width
    barcode_height = int(barcode_image.height * barcode_ratio)
    barcode_image = barcode_image.resize((max_barcode_width, barcode_height))
    barcode_x = (width - barcode_image.width) // 2
    canvas.paste(barcode_image, (barcode_x, 1200))

    footer_y = height - 170
    draw.line((120, footer_y, width - 120, footer_y), fill="#d8c4a6", width=3)
    draw.text((120, footer_y + 30), "Generated by Golden Dragon Tours Portal", font=_load_font(22), fill="#6a6258")
    draw.text((width - 430, footer_y + 30), ticket.created_at.strftime("Created %b %d, %Y %H:%M"), font=_load_font(22), fill="#6a6258")

    pdf_buffer = BytesIO()
    canvas.save(pdf_buffer, "PDF", resolution=100.0)
    pdf_buffer.seek(0)
    return pdf_buffer
