from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm, forms
from django.views.decorators.http import require_POST
from django.contrib import messages
from .forms import RegisterForm, TicketForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Ticket

import os
from io import BytesIO
from django.core.files.base import ContentFile
import barcode
from barcode.writer import ImageWriter
from PIL import Image, ImageDraw, ImageFont
import cloudinary.uploader



def _load_font(size, bold=False):
    font_names = ['DejaVuSans-Bold.ttf', 'arialbd.ttf'] if bold else ['DejaVuSans.ttf', 'arial.ttf']
    for font_name in font_names:
        try:
            return ImageFont.truetype(font_name, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


def _build_barcode_image(reference_code):
    code128 = barcode.get('code128', reference_code, writer=ImageWriter())
    barcode_buffer = BytesIO()
    code128.write(
        barcode_buffer,
        options={
            'module_width': 0.28,
            'module_height': 18,
            'font_size': 14,
            'text_distance': 6,
            'quiet_zone': 2,
        },
    )
    barcode_buffer.seek(0)
    return Image.open(barcode_buffer).convert('RGB')


def _build_ticket_pdf(ticket):
    width, height = 1240, 1754
    canvas = Image.new('RGB', (width, height), '#f7f1e8')
    draw = ImageDraw.Draw(canvas)

    draw.rounded_rectangle((70, 70, width - 70, height - 70), radius=36, fill='white', outline='#d8c4a6', width=4)
    draw.rounded_rectangle((70, 70, width - 70, 290), radius=36, fill='#163020')
    draw.text((120, 120), 'Golden Dragon Tours', font=_load_font(54, bold=True), fill='white')
    draw.text((120, 190), 'Digital Travel Ticket', font=_load_font(30), fill='#f3dfc1')

    draw.rounded_rectangle((120, 340, width - 120, 980), radius=28, fill='#fbf7f1', outline='#eadcc8', width=3)
    draw.text((150, 385), 'Booking Details', font=_load_font(34, bold=True), fill='#163020')

    details = [
        ('Reference Code', ticket.reference_code),
        ('Guest Name', ticket.full_name),
        ('Email', ticket.email),
        ('Phone', ticket.phone),
        ('Nationality', ticket.nationality),
        ('Tour Package', ticket.tour_package.name if ticket.tour_package else 'Not selected'),
        ('Travel Date', ticket.travel_date.strftime('%B %d, %Y')),
        ('Quantity', str(ticket.quantity)),
        ('Status', ticket.get_status_display()),
    ]

    y = 455
    for label, value in details:
        draw.text((160, y), label, font=_load_font(24, bold=True), fill='#8a6f4d')
        draw.text((160, y + 38), str(value), font=_load_font(30), fill='#1f1f1f')
        y += 95

    draw.rounded_rectangle((120, 1035, width - 120, 1510), radius=28, fill='#fffdfa', outline='#eadcc8', width=3)
    draw.text((150, 1080), 'Entry Barcode', font=_load_font(34, bold=True), fill='#163020')
    draw.text((150, 1135), 'Present this PDF or the on-screen ticket at the point of entry.', font=_load_font(24), fill='#6a6258')

    barcode_image = _build_barcode_image(ticket.reference_code)
    max_barcode_width = width - 360
    barcode_ratio = max_barcode_width / barcode_image.width
    barcode_height = int(barcode_image.height * barcode_ratio)
    barcode_image = barcode_image.resize((max_barcode_width, barcode_height))
    barcode_x = (width - barcode_image.width) // 2
    canvas.paste(barcode_image, (barcode_x, 1200))

    footer_y = height - 170
    draw.line((120, footer_y, width - 120, footer_y), fill='#d8c4a6', width=3)
    draw.text((120, footer_y + 30), 'Generated by Golden Dragon Tours Portal', font=_load_font(22), fill='#6a6258')
    draw.text((width - 430, footer_y + 30), ticket.created_at.strftime('Created %b %d, %Y %H:%M'), font=_load_font(22), fill='#6a6258')

    pdf_buffer = BytesIO()
    canvas.save(pdf_buffer, 'PDF', resolution=100.0)
    pdf_buffer.seek(0)
    return pdf_buffer


def home(request):
    return render(request, 'portal/home.html')


class RegisterForm(UserCreationForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control custom-input',
            'placeholder': 'Enter email address'
        })
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control custom-input',
                'placeholder': 'Choose a username'
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control custom-input',
            'placeholder': 'Create a password'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control custom-input',
            'placeholder': 'Confirm your password'
        })


def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Account created successfully.")
            return redirect('dashboard')
    else:
        form = RegisterForm()
    return render(request, 'portal/register.html', {'form': form})



class PortalAuthForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control custom-input',
            'placeholder': 'Enter username',
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control custom-input',
            'placeholder': 'Enter password',
        })


class PortalLoginView(LoginView):
    template_name = 'portal/login.html'
    form_class = PortalAuthForm

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Login successful. Welcome back!')
        return response


    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password. Please try again.')
        return super().form_invalid(form)


@require_POST
@login_required
def logout_view(request):
    logout(request)
    messages.success(request, 'Logged out successfully.')
    return redirect('login')


@login_required
def dashboard(request):
    form = TicketForm()
    tickets = Ticket.objects.filter(user=request.user).order_by('-created_at')
    return render(request, 'portal/dashboard.html', {'form': form, 'tickets': tickets})



@login_required
def create_ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.status = 'pending'  # always starts as pending
            ticket.save()

            try:
                code128 = barcode.get('code128', ticket.reference_code, writer=ImageWriter())
                buffer = BytesIO()
                code128.write(buffer)
                buffer.seek(0)

                result = cloudinary.uploader.upload(
                    buffer,
                    public_id=f"barcodes/{ticket.reference_code}",
                    resource_type="image"
                )
                ticket.barcode_image = result['public_id']
                ticket.save()

            except Exception as e:
                print(f"Barcode generation/upload error: {e}")
                messages.warning(request, f'Ticket created but barcode failed: {e}')

            messages.success(request, 'Ticket submitted successfully! Status: Pending.')
            return redirect('ticket_success', ticket_id=ticket.id)
        else:
            messages.error(request, 'Please fix the errors below.')
            tickets = Ticket.objects.filter(user=request.user).order_by('-created_at')
            return render(
                request,
                'portal/dashboard.html',
                {
                    'form': form,
                    'tickets': tickets,
                    'open_ticket_modal': True,
                },
            )

    return redirect('dashboard')



@login_required
def ticket_success(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id, user=request.user)
    return render(request, 'portal/ticket_success.html', {'ticket': ticket})


@login_required
def download_ticket_pdf(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id, user=request.user)
    pdf_buffer = _build_ticket_pdf(ticket)

    response = HttpResponse(pdf_buffer.getvalue(), content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="ticket-{ticket.reference_code}.pdf"'
    return response
